### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by dschwilk** [jaspkau/pico_growth#2]
Code refers to data files that do not exist.

```R
data <- read.delim("data/env.csv", sep = ",")
data <- read_excel("data/env.xlsx", sheet = 1)
```
Both lines result in errors.  The data folder has the following files only:

`env_avg.csv` and  `pico_growth_met.xlsx`

**Comment by jaspkau** [comment]
I have updated the environ_panel script. The command for reading csv file has been deleted as it was redundant.

And I have uploaded the missing excel file.
